### ISSUE TITLE
Saving the image after calculating

### ISSUE THREAD

**Issue by hendrikbgr** [cielito-lindo-productions/primitive.nextgen#2]
Hello,
there are currently (10.05.2018) two options to save the image: Raster image and Vector image.
When I choose the Raster image it tells you: "Raster image: After calculating you can save the image as png". I am now finished with calculating but I dont see a way of saving the image. I cant right click it either. Can somebody tell he how to save the images as an png.
Thanks

**Comment by cielito-lindo-productions** [comment]
Hi,
good to hear from you.
Well, normally the "Save as dialog" pops ups and there you can select the name and path of the file and then also save it.
Which operating system in which version are you using?
If saving as image doesn't work for you you could try the other appreach: Copy and paste the Vector image code in a file with the ending .svg and open it in inkscape. From there you export as png, jpg ...

**Comment by hendrikbgr** [comment]
Hi,
I am afraid the "Save as dialog" does not pop up for me. I am using OSX 10.13.3.
Thank you for the tip with the .svg file. I totally forgot about that option.
Thank you very much for the quick reply.
Regards
Hendrik B.

**Comment by cielito-lindo-productions** [comment]
Hi,
good to know that you found a solution that works for you. ;-)
Unfortunately OS X is currently not supported as I don't have a device to test it.
Regards,
Cielito Lindo Produtions
